env:
  browser: true
  es2021: true
extends:
  - "airbnb-base"
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  quotes: ["warn", "double"]
  object-curly-newline: [ "error", {
    "ObjectExpression": "always",
    "ObjectPattern": { "multiline": true },
    "ImportDeclaration": "never",
    "ExportDeclaration": { "multiline": true, "minProperties": 3 }
  } ]
