name: lint-check

on: push

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: install all dependencies
        run: make install-all

      - name: run linter
        run: make lint
